name: Deploy to GitHub Pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          cd docs && npm ci
        env:
          NODE_ENV: production

      - name: Build Astro app
        run: |
          cd docs && npm run build

      - name: Build examples
        run: |
          for example in vite-vanilla vite-vue vite-react vite-angular; do
            echo "Building $example..."
            cd examples/$example
            npm ci
            npm run build
            cd ../..
            mkdir -p docs/dist/examples/$example
            cp -r examples/$example/dist/* docs/dist/examples/$example/
          done
          # Copy CDN example as-is
          mkdir -p docs/dist/examples/cdn
          cp -r examples/cdn/* docs/dist/examples/cdn/

      - name: Verify build output
        run: |
          ls -la docs/dist/
          echo "Build completed successfully"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
